GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "chad",
    "number": "3-912-0312731"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Maria"
}
### 
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "3-912-0312731"
}